# Generated by Django 3.1 on 2021-06-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_poly'),
    ]

    operations = [
        migrations.AddField(
            model_name='poly',
            name='color',
            field=models.CharField(default='FFFFFF', max_length=10),
            preserve_default=False,
        ),
    ]
