# Generated by Django 3.1 on 2021-06-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_poly_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poly',
            old_name='color',
            new_name='fill',
        ),
    ]
