# Generated by Django 3.1 on 2021-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210612_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='first_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poly',
            name='business_kind',
            field=models.CharField(default='asd', max_length=64),
            preserve_default=False,
        ),
    ]
