# Generated by Django 3.1 on 2021-06-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210613_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poly',
            name='business_kind',
        ),
    ]
