# Generated by Django 3.1 on 2021-06-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_poly_business_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poly',
            old_name='business_type',
            new_name='business_kind',
        ),
    ]
