# Generated by Django 3.1 on 2021-06-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210613_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
